version: '3'
services:
  service-discovery-container:
    image: hoangtien2k3/service-discovery-ecommerce-boot:0.1.0
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=dev



