
version: '3'
services:
  shipping-service-container:
    image: hoangtien2k3/shipping-service-ecommerce-boot:0.1.0
    ports:
      - 8600:8600
    environment:
      - SPRING_PROFILES_ACTIVE=dev



